[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "adesyn"
version = "0.1"
description = "ADESyn cGAN package"
dependencies = [
    "torch",
    "numpy<2",
]